{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ksf",
    "module": "liveness",
    "version": "4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "liveness-1.0.aar",
          "url": "liveness-1.0.aar",
          "size": 77225803,
          "sha512": "add7b111b45c8dbd8954be678eed5a0b1192e0b23ae893113a3db6684eacd092ecbe46e00a8839dd21d3a6ea39f55f6a5eccd649397e3b08b43dd7f562e0bd32",
          "sha256": "a009fa655f5d564e37f74a52c5a51dddfe56050dd5a926eb535be77802e16d91",
          "sha1": "5053c92540606dc5a5851d285caf2a6f3cf67b64",
          "md5": "0e24a9612c39ad1862cfcd56847f3f10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "SdkTest.liveness",
          "module": "openCVLibrary343",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "liveness-1.0.aar",
          "url": "liveness-1.0.aar",
          "size": 77225803,
          "sha512": "add7b111b45c8dbd8954be678eed5a0b1192e0b23ae893113a3db6684eacd092ecbe46e00a8839dd21d3a6ea39f55f6a5eccd649397e3b08b43dd7f562e0bd32",
          "sha256": "a009fa655f5d564e37f74a52c5a51dddfe56050dd5a926eb535be77802e16d91",
          "sha1": "5053c92540606dc5a5851d285caf2a6f3cf67b64",
          "md5": "0e24a9612c39ad1862cfcd56847f3f10"
        }
      ]
    }
  ]
}
